### ISSUE TITLE
Cannot add LAG interface to VLAN interface as tagged port

### ISSUE THREAD

**Issue by james-jra** [open-switch/opx-cps#67] opened 2018-03-01 12:13 UTC
The CPS transaction to add a LAG interface to a VLAN interface as a tagged port always fails.
The same transaction for an untagged port succeeds.

The trace below demonstrates this behavior.
Note, I've added some print statements to the OPX utilities `cps_config_vlan.py` and `cps_config_lag.py` to help troubleshooting.
The diff of these exact changes can be found at the end of this post.

### Summary ###

* Create a LAG interface `bnd1`
* Create a VLAN interface `br10`
* Add `bnd1` to `br10` as an tagged-port. This fails
* Doing the same thing, but adding `bnd1` as an untagged-port succeeds.

### Trace ###

Create LAG interface:
```
opxUser@opx_vm:~$ sudo cps_config_lag.py --create --lname bnd1

Performing: rpc
With CPS object: {'data': {'if/interfaces/interface/type': bytearray(b'ianaift:ieee8023adLag\x00'), 'dell-base-if-cmn/set-interface/input/operation': bytearray(b'\x01\x00\x00\x00'), 'if/interfaces/interface/name': bytearray(b'bnd1\x00')}, 'key': '1.19.1245192.'}

Success

Returned object: [{'operation': 'rpc', 'change': {'operation': 'action', 'data': {'dell-base-if-cmn/if/interfaces/interface/if-index': bytearray(b'4\x00\x00\x00'), 'dell-if/if/interfaces/interface/phys-address': bytearray(b'08:00:27:c8:2a:5b\x00'), 'if/interfaces/interface/name': bytearray(b'bnd1\x00'), 'if/interfaces/interface/type': bytearray(b'ianaift:ieee8023adLag\x00'), 'cps/object-group/return-code': bytearray(b'\x00\x00\x00\x00'), 'dell-base-if-cmn/set-interface/input/operation': bytearray(b'\x01\x00\x00\x00')}, 'key': '1.19.1245192.'}}]
```

Create VLAN interface:
```
opxUser@opx_vm:~$ sudo cps_config_vlan.py --add --id 10 --vlantype 1

Performing: rpc
With CPS object: {'data': {'dell-if/if/interfaces/interface/untagged-ports': [bytearray(b'')], 'dell-if/if/interfaces/interface/vlan-type': bytearray(b'\x01\x00\x00\x00'), 'base-if-vlan/if/interfaces/interface/id': bytearray(b'\n\x00'), 'if/interfaces/interface/type': bytearray(b'ianaift:l2vlan\x00'), 'dell-base-if-cmn/set-interface/input/operation': bytearray(b'\x01\x00\x00\x00')}, 'key': '1.19.1245192.'}

Success

Returned object: [{'operation': 'rpc', 'change': {'operation': 'action', 'data': {'dell-base-if-cmn/if/interfaces/interface/if-index': bytearray(b'5\x00\x00\x00'), 'dell-if/if/interfaces/interface/phys-address': bytearray(b'08:00:27:c8:2a:5c\x00'), 'base-if-vlan/if/interfaces/interface/id': bytearray(b'\n\x00'), 'dell-if/if/interfaces/interface/untagged-ports': [bytearray(b'')], 'if/interfaces/interface/type': bytearray(b'ianaift:l2vlan\x00'), 'cps/object-group/return-code': bytearray(b'\x00\x00\x00\x00'), 'dell-if/if/interfaces/interface/vlan-type': bytearray(b'\x01\x00\x00\x00'), 'dell-base-if-cmn/set-interface/input/operation': bytearray(b'\x01\x00\x00\x00')}, 'key': '1.19.1245192.'}}]
```

Add LAG interface to VLAN interface as tagged-port:
```
opxUser@opx_vm:~$ sudo cps_config_vlan.py --addport --name br10 --port bnd1 --tagged

Performing: rpc
With CPS object: {'data': {'dell-base-if-cmn/set-interface/input/operation': bytearray(b'\x03\x00\x00\x00'), 'if/interfaces/interface/name': bytearray(b'br10\x00'), 'dell-if/if/interfaces/interface/tagged-ports': [bytearray(b'bnd1\x00')]}, 'key': '1.19.1245192.'}

Failed  <------ !

Returned object: [{'operation': 'rpc', 'change': {'operation': 'action', 'data': {'cps/object-group/return-code': bytearray(b'\x01\x00\x00\x00'), 'dell-base-if-cmn/set-interface/input/operation': bytearray(b'\x03\x00\x00\x00'), 'if/interfaces/interface/name': bytearray(b'br10\x00'), 'dell-if/if/interfaces/interface/tagged-ports': [bytearray(b'bnd1\x00')]}, 'key': '1.19.1245192.'}}]

```

Starting with a fresh VLAN interface, try and add LAG interface as untagged-port:
```
opxUser@opx_vm:~$ sudo cps_config_vlan.py --addport --name br10 --port bnd1

Performing: rpc
With CPS object: {'data': {'dell-if/if/interfaces/interface/untagged-ports': [bytearray(b'bnd1\x00')], 'dell-base-if-cmn/set-interface/input/operation': bytearray(b'\x03\x00\x00\x00'), 'if/interfaces/interface/name': bytearray(b'br10\x00')}, 'key': '1.19.1245192.'}

Success  <------ !

Returned object: [{'operation': 'rpc', 'change': {'operation': 'action', 'data': {'dell-if/if/interfaces/interface/untagged-ports': [bytearray(b'bnd1\x00')], 'dell-base-if-cmn/set-interface/input/operation': bytearray(b'\x03\x00\x00\x00'), 'if/interfaces/interface/name': bytearray(b'br10\x00'), 'cps/object-group/return-code': bytearray(b'\x00\x00\x00\x00')}, 'key': '1.19.1245192.'}}]

```

#### trace changes ####

What follows is the trace I added to the OPX configuration utilities

nas_ut_framework.py
```
$ git diff nas_ut_framework.py
diff --git a/scripts/lib/python/nas_ut_framework.py b/scripts/lib/python/nas_ut_framework.py
index 989175e..8e0d649 100755
--- a/scripts/lib/python/nas_ut_framework.py
+++ b/scripts/lib/python/nas_ut_framework.py
@@ -28,7 +28,7 @@ def commit(obj, op):
         return l

     print "Failed"
-    return False
+    return l


 def create(obj):
```

cps_config_vlan.py
```
$ git diff cps_config_vlan.py
diff --git a/scripts/bin/cps_config_vlan.py b/scripts/bin/cps_config_vlan.py
index 8b1ed9a..bd81cf8 100755
--- a/scripts/bin/cps_config_vlan.py
+++ b/scripts/bin/cps_config_vlan.py
@@ -38,7 +38,10 @@ def nas_vlan_op(op, data_dict):
             return False
         obj = cps_object.CPSObject( intf_rpc_key_id, data=data_dict)
         op = 'rpc'
-    nas_ut.get_cb_method(op)(obj)
+        print("\nPerforming: {}".format(op))
+        print("With CPS object: {}\n".format(obj.get()))
+    print("\nReturned object: {}".format(nas_ut.get_cb_method(op)(obj)))
+
```

cps_config_lag.py
```
$ git diff cps_config_lag.py
diff --git a/scripts/bin/cps_config_lag.py b/scripts/bin/cps_config_lag.py
index 42bbeb6..d32de98 100755
--- a/scripts/bin/cps_config_lag.py
+++ b/scripts/bin/cps_config_lag.py
@@ -43,7 +43,9 @@ def nas_lag_op(op, data_dict,commit=True):
         op = 'rpc'
     obj.add_attr("if/interfaces/interface/type","ianaift:ieee8023adLag")
     if commit:
-        nas_ut.get_cb_method(op)(obj)
+        print("\nPerforming: {}".format(op))
+        print("With CPS object: {}\n".format(obj.get()))
+        print("\nReturned object: {}".format(nas_ut.get_cb_method(op)(obj)))
     else:
         return (obj, op)
```

**Comment by atanu-mandal** [comment] 2018-03-02 03:49
Thanks @james-jra for the detailed description of the issue and  the steps to reproduce. It really helps.

The issue seems to be with not having “dummy0” interface in kernel (please check that on your target).

The linux kernel has a limitation that we can only add a bond to vlan(i.e. bridge) when the bond has a member port. So “dummy0” is used for that purpose.

If we create the interface manually that should solve this hopefully.
To create "dummy0" interface -

''' **_cps_set_oid.py -qua target -oper action dell-base-if-cmn/set-interface dell-base-if-cmn/set-interface/input/operation=1 if/interfaces/interface/name=dummy0    if/interfaces/interface/type=ianaift:softwareLoopback_** '''

We are looking into the root cause of missing "dummy0" interface from the kernel.

**Comment by atanu-mandal** [comment] 2018-03-02 07:03
To follow up on the “dummy0” interface, we just need to execute “modprobe dummy” (that would create the “dummy0” interface).

root@OPX:~# ifconfig dummy0
dummy0: error fetching interface information: Device not found

root@OPX:~# modprobe dummy

root@OPX:~# ifconfig dummy0
dummy0    Link encap:Ethernet  HWaddr da:ac:6a:36:80:25
          BROADCAST NOARP  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

We are going to fix this issue (by enabling this at startup). 
Please run the above command till we fix the issue.

**Comment by atanu-mandal** [comment] 2018-03-02 08:24
Fix is in review
https://review.openswitch.net/#/c/14571/

**Comment by atanu-mandal** [comment] 2018-03-06 04:35
The fix is merged. I am closing this issue,

**Closed by atanu-mandal** 2018-03-06 04:35 UTC
